### ISSUE TITLE
[Bug] yesoreyeram-infinity-datasource is not correctly provisioned 

### ISSUE THREAD

**Issue by magaton** [yesoreyeram/grafana-infinity-datasource#51]
**Describe the bug**
yesoreyeram-infinity-datasource is not correctly provisioned 

For the following datasources.yaml:
```
apiVersion: 1
datasources:
  - id: 1
    orgId: 1
    name: "Infinity-Local"
    type: "yesoreyeram-infinity-datasource"
    typeLogoUrl: "public/plugins/yesoreyeram-infinity-datasource/img/icon.svg"
    access: "proxy"
    url: "http://localhost:4001/graphql"
    password: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    readOnly: false
    editable: true
    jsonData: {
        datasource_mode: "advanced"
    }
   ```

in grafana datsources, the jsonData has been ignored and url is not correctly resolved.

**Screenshots**
<img width="743" alt="Screenshot 2021-03-22 at 15 02 57" src="https://user-images.githubusercontent.com/4103157/112002048-ccbb3500-8b1f-11eb-8b0c-8a762920881c.png">

**Version Details:**
 - Grafana version : 7.3.5
 - Plugin version : 0.6.0

**Additional context**
