### ISSUE TITLE
[Bug] Can't override `Host` header

### ISSUE THREAD

**Issue by ColdFire87** [yesoreyeram/grafana-infinity-datasource#634]
## **Describe the bug**

The plugin does not allow overwriting the `Host` header.

## **Steps to reproduce**

```yaml
{{- if .Values.datasources.scraper.url }}
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: lambda-scraper
  labels:
    app: grafana
    grafana: local
spec:
  name: datasource-lambda-scraper.yaml
  datasources:
    - name: Lambda Scraper
      type: yesoreyeram-infinity-datasource
      uid: lambda-scraper
      # Call into `aws-sigv4-proxy` sidecar container
      url: "http://localhost:8080"
      isDefault: false
      customJsonData:
        readOnly: true
        # `aws-sigv4-proxy` will sign the request with AWS creds,
        # then forward it to the URL specified in the `Host` header
        httpHeaderName1: "Host"
        httpHeaderValue1: "{{ .Values.datasources.scraper.url }}"
        allowedHosts:
          - "http://localhost:8080"
{{- end }}
```

Instead of overwriting the `Host` header with my desired URL, `localhost:8080` is used **(see first screenshot)**.

Even when manually setting the header via the plugin UI in Grafana, the result is the same **(see second screenshot)**.

## **Sample Data**

No sample data required.

## **Screenshots**

![image](https://github.com/yesoreyeram/grafana-infinity-datasource/assets/14059086/f85e2d0a-87b2-4c4c-96d3-c380d462493f)

![image](https://github.com/yesoreyeram/grafana-infinity-datasource/assets/14059086/2fda1102-ff54-4424-9153-4769ecb9be28)

## **Version Details:**

- Grafana version : v10.0.2 (b2bbe10fbc)
- Plugin version : 2.0.0

## **Additional context**

I want to invoke an AWS Lambda, using a Lambda URL with AWS_IAM authentication. In order to do so, I need to sign
the request with AWS Sigv4, which the plugin doesn't support yet. To get around this limitation, I chose to use
https://github.com/awslabs/aws-sigv4-proxy, which is deployed as a sidecar container inside the pod running grafana.

Grafana is configured with access to invoke the Lambda URL, via IRSA.

Using `aws-sigv4-proxy` locally works fine:

```shell
# Run aws-sigv4-proxy
docker run --rm -ti \
  -v ~/.aws:/root/.aws \
  -p 8080:8080 \
  public.ecr.aws/aws-observability/aws-sigv4-proxy:latest -v --name lambda --region eu-west-1 --port :8080

# Make request
curl -X 'GET' -H 'Accept: application/json;q=0.9,text/plain' \
  -H 'Host: xxxxx.lambda-url.eu-west-1.on.aws' \
  'http://localhost:8080/abc'
```

Ideally, the plugin would support AWS_IAM authentication out of the box (either at the data source level, or on
a pre-request level, via a checkbox in the plugin UI). Other data source plugins already have support for it:
- https://github.com/grafana/grafana/tree/main/public/app/plugins/datasource/cloudwatch
- https://grafana.com/grafana/plugins/grafana-x-ray-datasource/
- https://grafana.com/grafana/plugins/grafana-athena-datasource/

I don't have any experience developing Grafana plugins, and I don't know if a general AWS Sigv4 is doable,
or it needs to be coupled to a particular AWS service (in this case Lambda invocation via LambdaURL).

The X-Ray data source states:
> Currently all access to X-Ray is done server-side by the Grafana backend using the official AWS SDK. If your Grafana server is running on AWS you can use IAM Roles and authentication will be handled automatically.
