### ISSUE TITLE
[Bug] Plugin does not work with readOnlyRootFilesystem

### ISSUE THREAD

**Issue by jkroepke** [yesoreyeram/grafana-infinity-datasource#690]
## **Describe the bug**

We deploy Grafana with `readOnlyRootFilesystem` setting. The Container Filesystem is readonly by default, except /var/lib/grafana
and /tmp.

If / is mounted as readonly, the plugin return `Status: 500. Message: error getting data frame. 400 Bad Request`. However if we disable readonly mount, the plugin works fine. 

## **Steps to reproduce**

1. Deploy Grafana using the helm chart and the values below:
```yaml
containerSecurityContext:
  readOnlyRootFilesystem: true
extraEmptyDirMounts:
  - name: tmp
     mountPath: /tmp
```

**Note:** bugs will be fixed only if enough information provided to reproduce the issue

## **Sample Data**

Any issue with any data

## **Screenshots**

![image](https://github.com/yesoreyeram/grafana-infinity-datasource/assets/1560587/94576a9f-24c1-479b-b927-112564894db8)

## **Version Details:**

- Grafana version : 10.1.2
- Plugin version : 2.0.0

## **Additional context**

I may ask, if the plugin write data is the disk and if yes where.
